<?php
header("Content-type: text/html; charset=utf8");
require("../../conexion.php"); 

  $ID_CANDIDATO = $_POST['ID_CANDIDATO'];
  
  $ID_EVALUACION = $_POST['ID_EVALUACION'];
  $CURP = $_POST['CURP'];
  $FECHA_DE_REEXAMINACION = $_POST['FECHA_DE_REEXAMINACION'];
  $AREA_REEXAMINAR = $_POST['AREA_REEXAMINAR'];
  $SE_PRESENTO = $_POST['SE_PRESENTO'];
  $OFICIO_LIBERACION = $_POST['OFICIO_LIBERACION'];
  $OFICIO_LIBERACION_REEXAMINACION = $_POST['OFICIO_LIBERACION_REEXAMINACION'];
  $RESULTADO_TECNICO = $_POST['RESULTADO_TECNICO'];
  $RESULTADO_TECNICO_REEXAMINACION = $_POST['RESULTADO_TECNICO_REEXAMINACION'];
  $TECNICA = $_POST['TECNICA'];
  $STATUS_DE_EVALUACION = $_POST['STATUS_DE_EVALUACION'];
  $RESULTADO_FINAL_POLIGRAFIA = $_POST['RESULTADO_FINAL_POLIGRAFIA'];
  $MOTIVO_NO_APROBADO = $_POST['MOTIVO_NO_APROBADO'];
  $ADMISIONES = $_POST['ADMISIONES'];
  $ADMISIONES_REEXAMINACION = $_POST['ADMISIONES_REEXAMINACION'];
  $INFORMACION = $_POST['INFORMACION'];
  $BENEFICIOS = $_POST['BENEFICIOS'];
  $INFO_CONF = $_POST['INFO_CONF'];
  $FAV_DEL = $_POST['FAV_DEL'];
  $DROGAS = $_POST['DROGAS'];
  $DELITOS = $_POST['DELITOS'];
  $DEL_ORG = $_POST['DEL_ORG'];
  $SIST_DE_CALIF = $_POST['SIST_DE_CALIF'];
  $SIST_ALIF_REEXAMINACION = $_POST['SIST_ALIF_REEXAMINACION'];
  $OBSERVACIONES = $_POST['OBSERVACIONES'];
  $RESULTADO_TECNICO_REAL = $_POST['RESULTADO_TECNICO_REAL']; 
  $RESULTADO_REAL_REEXAMINACION = $_POST['RESULTADO_REAL_REEXAMINACION'];
  $ADMISION_EN_REEXAMINACION_EN_AREA = $_POST['ADMISION_EN_REEXAMINACION_EN_AREA'];
  $CASOS_CONTUNDENTES_DT = $_POST['CASOS_CONTUNDENTES_DT'];
  $REEXAMINACION_CONFIRMA_DT = $_POST['REEXAMINACION_CONFIRMA_DT'];
  $RELACION_ENTRE_CI_DT = $_POST['RELACION_ENTRE_CI_DT'];
  $CASO_DEFINIDO = $_POST['CASO_DEFINIDO'];
  $REEXAMINACION_DEFINIO_CON = $_POST['REEXAMINACION_DEFINIO_CON'];
  $REEXAMINACION_AGREGO_INFORMACION = $_POST['REEXAMINACION_AGREGO_INFORMACION'];
  $DETECCION_CONTUNDENTE = $_POST['DETECCION_CONTUNDENTE'];
  $DETECCION_CONTUNDENTE_REEX  = $_POST['DETECCION_CONTUNDENTE_REEX'];
  $CAMBIA_AREA = $_POST['CAMBIA_AREA'];
  $OBSERVACIONES_REEX = $_POST['OBSERVACION_REEX'];
  $BENEFICIOS_REEX = $_POST['BENEFICIOS_REEX'];
  $INFO_CONF_REEX = $_POST['INFO_CONF_REEX'];
  $FAV_DEL_REEX = $_POST['FAV_DEL_REEX'];
  $DROGAS_REEX = $_POST['DROGAS_REEX'];
  $DELITOS_REEX = $_POST['DELITOS_REEX'];
  $DEL_ORG_REEX = $_POST['DEL_ORG_REEX'];

  $sqlDel = ("DELETE FROM calificacion WHERE ID_EVALUACION = '$ID_EVALUACION'");

    if ($conexion->query($sqlDel) === TRUE) {
      echo "true";
     } 

  $sql = ("INSERT INTO calificacion  VALUES ('$ID_CANDIDATO', '', '', '$ID_EVALUACION', '$CURP', '$FECHA_DE_REEXAMINACION', '$AREA_REEXAMINAR', '$SE_PRESENTO', '$OFICIO_LIBERACION', '$OFICIO_LIBERACION_REEXAMINACION', '$RESULTADO_TECNICO', '$RESULTADO_TECNICO_REEXAMINACION', '$TECNICA', '$STATUS_DE_EVALUACION', '$RESULTADO_FINAL_POLIGRAFIA', '$MOTIVO_NO_APROBADO', '$ADMISIONES', '$ADMISIONES_REEXAMINACION', '$INFORMACION', '$BENEFICIOS', '$INFO_CONF', '$FAV_DEL', '$DROGAS', '$DELITOS', '$DEL_ORG', '$SIST_DE_CALIF', '$SIST_ALIF_REEXAMINACION', '$OBSERVACIONES', '$RESULTADO_TECNICO_REAL', '$RESULTADO_REAL_REEXAMINACION', '$ADMISION_EN_REEXAMINACION_EN_AREA', '$CASOS_CONTUNDENTES_DT', '$REEXAMINACION_CONFIRMA_DT', '$RELACION_ENTRE_CI_DT', '$CASO_DEFINIDO', '$REEXAMINACION_DEFINIO_CON', '$REEXAMINACION_AGREGO_INFORMACION', '$DETECCION_CONTUNDENTE', '$DETECCION_CONTUNDENTE_REEX', '$CAMBIA_AREA')");
  $conexion->set_charset("utf8");

  if ($conexion->query($sql) === TRUE) {
      echo "true";
  } else {
      echo "false";
}
$conexion->close();


?>