<?php
{
    error_reporting(0);
    header("Content-type: text/html; charset=utf8");
    include "../../conection.php";
    include "../../MySqlConnect.php";

    //Datos del candidato
    $ID_CANDIDATO = $_POST['ID_CANDIDATO'];
    $ID_EVALUACION = $_POST['ID_EVALUACION'];
    $CURP = $_POST['CURP'];

    //Datos del evaluador
    $ID_EVALUADOR = $_POST['ID_EVALUADOR'];
    $ID_EVALUADOR_REEX = $_POST['ID_EVALUADOR_REEX'];

    //Datos de las calificaciones de poligrafía
    $SE_PRESENTO = $_POST['SE_PRESENTO'];
    $OFICIO_LIBERACION = $_POST['OFICIO_LIBERACION'];
    $RESULTADO_TECNICO = $_POST['RESULTADO_TECNICO'];
    $TECNICA = $_POST['TECNICA'];
    $STATUS_DE_EVALUACION = $_POST['STATUS_DE_EVALUACION'];
    $ADMISIONES = $_POST['ADMISIONES'];
    $RESULTADO_FINAL_POLIGRAFIA = $_POST['RESULTADO_FINAL_POLIGRAFIA'];
    $MOTIVO_NO_APROBADO = $_POST['MOTIVO_NO_APROBADO'];
    $SIST_DE_CALIF = $_POST['SIST_DE_CALIF'];
    $BENEFICIOS = $_POST['BENEFICIOS'];
    $INFO_CONF = $_POST['INFO_CONF'];
    $FAV_DEL = $_POST['FAV_DEL'];
    $DROGAS = $_POST['DROGAS'];
    $DELITOS = $_POST['DELITOS'];
    $DEL_ORG = $_POST['DEL_ORG'];
    $RESULTADO_TECNICO_REAL = $_POST['RESULTADO_TECNICO_REAL']; 
    $RELACION_ENTRE_CI_DT = $_POST['RELACION_ENTRE_CI_DT'];
    $DETECCION_CONTUNDENTE = $_POST['DETECCION_CONTUNDENTE'];
    $CASO_DEFINIDO = $_POST['CASO_DEFINIDO'];
    $OBSERVACIONES = $_POST['OBSERVACIONES'];
    
    //Datos de la reexaminación de poligrafía
    $FECHA_DE_REEXAMINACION = $_POST['FECHA_DE_REEXAMINACION'];
    $AREA_REEXAMINAR = $_POST['AREA_REEXAMINAR'];
    $OFICIO_LIBERACION_REEXAMINACION = $_POST['OFICIO_LIBERACION_REEXAMINACION'];
    $RESULTADO_TECNICO_REEXAMINACION = $_POST['RESULTADO_TECNICO_REEXAMINACION'];
    $ADMISIONES_REEXAMINACION = $_POST['ADMISIONES_REEXAMINACION'];
    $BENEFICIOS_REEX = $_POST['BENEFICIOS_REEX'];
    $INFO_CONF_REEX = $_POST['INFO_CONF_REEX'];
    $FAV_DEL_REEX = $_POST['FAV_DEL_REEX'];
    $DROGAS_REEX = $_POST['DROGAS_REEX'];
    $DELITOS_REEX = $_POST['DELITOS_REEX'];
    $DEL_ORG_REEX = $_POST['DEL_ORG_REEX'];
    $SIST_CALIF_REEXAMINACION = $_POST['SIST_CALIF_REEXAMINACION'];
    $RESULTADO_REAL_REEXAMINACION = $_POST['RESULTADO_REAL_REEXAMINACION'];
    $ADMISION_EN_REEXAMINACION_EN_AREA = $_POST['ADMISION_EN_REEXAMINACION_EN_AREA'];
    /**/$INFO_RIESGO = $_POST['CONTEXTO'];
    $REEXAMINACION_CONFIRMA_DT = $_POST['REEXAMINACION_CONFIRMA_DT'];
    $REEXAMINACION_DEFINIO_CON = $_POST['REEXAMINACION_DEFINIO_CON'];
    $REEXAMINACION_AGREGO_INFORMACION = $_POST['REEXAMINACION_AGREGO_INFORMACION'];
    $DETECCION_CONTUNDENTE_REEX  = $_POST['DETECCION_CONTUNDENTE_REEX'];
    $CAMBIA_AREA_DT_REEX = $_POST['CAMBIA_AREA'];
    $OBSERVACIONES_REEX = $_POST['OBSERVACION_REEX'];
    $OBSERVACIONES_CONFIRMA_DT = $_POST['OBSERVACION_CONFIRMA_DT'];

    $conexion = new MySqlConnect($db, $user, $pswd);
    $ResultQuery = sprintf("SELECT MODO_EVALUACION AS ROW FROM EVALUACION WHERE ID_EVALUACION = '%s'", $ID_EVALUACION);
    $ModoEvaluacion = $conexion->getSingleValueFromQuery($ResultQuery);

    $Id_Evaluador_Reex = "";
    $Id_Evaluador = "";
    if (!empty($ModoEvaluacion))
    {
        if (strcmp($ModoEvaluacion, "EXTRAORDINARIA") == 0)
        {
            $Id_Evaluador_Reex = $ID_EVALUADOR;
            $Id_Evaluador = $conexion->getSingleValueFromQuery(sprintf("SELECT ID_EVALUADOR AS ROW FROM CALIFICACION WHERE ID_EVALUACION = '%s'", $ID_EVALUACION));
        }
        else
        {
            $Id_Evaluador = $ID_EVALUADOR;
            $Id_Evaluador_Reex = "";
        }
    }
    echo "Fuera del primer IF";
    $delRecordQuery = sprintf("DELETE FROM CALIFICACION WHERE ID_EVALUACION = '%s';", $ID_EVALUACION);
    $addCalifInfoQuery = sprintf("INSERT INTO CALIFICACION VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', %d, %d, %d, %d, %d, %d, 
    '%s', '%s', '%s', '%s', '%s', /**/'%s', '%s', '%s', '%s', '%s', %d, %d, %d, %d, %d, %d, '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');", 
    $ID_CANDIDATO, $ID_EVALUACION, $CURP, $Id_Evaluador, $Id_Evaluador_Reex, $SE_PRESENTO, $OFICIO_LIBERACION, $RESULTADO_TECNICO, $TECNICA, $STATUS_DE_EVALUACION, $ADMISIONES, $RESULTADO_FINAL_POLIGRAFIA, 
    $MOTIVO_NO_APROBADO, $SIST_DE_CALIF, $BENEFICIOS, $INFO_CONF, $FAV_DEL, $DROGAS, $DELITOS, $DEL_ORG, $RESULTADO_TECNICO_REAL, $RELACION_ENTRE_CI_DT, $DETECCION_CONTUNDENTE, 
    $CASO_DEFINIDO, $OBSERVACIONES, $FECHA_DE_REEXAMINACION, $AREA_REEXAMINAR, $OFICIO_LIBERACION_REEXAMINACION, $RESULTADO_TECNICO_REEXAMINACION, $ADMISIONES_REEXAMINACION, 
    $BENEFICIOS_REEX, $INFO_CONF_REEX, $FAV_DEL_REEX, $DROGAS_REEX, $DELITOS_REEX, $DEL_ORG_REEX, $SIST_CALIF_REEXAMINACION, $RESULTADO_REAL_REEXAMINACION, $ADMISION_EN_REEXAMINACION_EN_AREA, 
    $INFO_RIESGO, $REEXAMINACION_CONFIRMA_DT, $REEXAMINACION_DEFINIO_CON, $REEXAMINACION_AGREGO_INFORMACION, $DETECCION_CONTUNDENTE_REEX, $CAMBIA_AREA_DT_REEX, $OBSERVACIONES_REEX, $OBSERVACIONES_CONFIRMA_DT);
    
    $conexion->executeInsertQuery($delRecordQuery.$addCalifInfoQuery, 2);
    echo "Cerrando conexión";
    $conexion->closeMySqlConnection();
}
?>