<?php
header("Content-type: text/html; charset=utf8");
header('Content-type:application/json');
require("../../conexion.php"); 

$FECHA1 = $_REQUEST['FECHA1'];
$FECHA2 = $_REQUEST['FECHA2'];
$lol = $_REQUEST['lol'];

$conexion->set_charset("utf8");



	if ($result = $conexion->query("SELECT DISTINCT CA.PRIMER_NOMBRE, IF(CA.SEGUNDO_NOMBRE != '' OR CA.SEGUNDO_NOMBRE != ' ', CA.SEGUNDO_NOMBRE, '') AS 'SEGUNDO_NOMBRE',CA.PRIMER_APELLIDO, IF (CA.SEGUNDO_APELLIDO != '' OR CA.SEGUNDO_APELLIDO != ' ', CA.SEGUNDO_APELLIDO, '') AS SEGUNDO_APELLIDO,
		IF(CI.CURP IS NULL,CA.CURP,CI.CURP) AS CURP,
		IF(CI.RFC IS NULL,'',CI.RFC) AS RFC,
		EV.FOLIO,
		IF(CI.TOX IS NULL,EV.FECHA_EXAMEN_TOXICOLOGICO,CI.TOX) AS TOX,
		EV.TIPO_EVALUACION,EV.MOTIVO_EVALUACION, O.DEPENDENCIA,O.PUESTO,O.CORPORACION ,EV.EVALUACION_DERIVADA_DE,
		IF(CI.INTEGRACION IS NULL,Cin.FECHA_RI,CI.INTEGRACION) AS INTEGRACION,
		IF(CI.PRESICION_PUESTO IS NULL,Cinf.C7,CI.PRESICION_PUESTO) AS PRESICION_PUESTO,
		IF(CI.INTEGRACION_R IS NULL,RIn.RESULTADO,CI.INTEGRACION_R) AS INTEGRACION_R
		FROM evaluacion EV 
			LEFT JOIN candidatos CA ON CA.ID_CANDIDATO = EV.ID_CANDIDATO 
			LEFT JOIN oficios O ON O.ID_EVALUACION = EV.ID_EVALUACION 
			LEFT JOIN reportes R ON R.ID_EVALUACION = EV.ID_EVALUACION 
			LEFT JOIN reporte_integracion RIn ON RIn.ID_EVALUACION = EV.ID_EVALUACION 
			LEFT JOIN reporte_ise RIse ON RIse.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN reportes_med RMed ON RMed.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN reportes RTox ON RTox.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN psicologia_reporte RPsi ON RPsi.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN reporte_poligrafia RPol ON RPol.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN concentrado_integracion Cin ON Cin.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN concentrado_informacion_resultados CI ON CI.ID_EVALUACION = EV.ID_EVALUACION
			LEFT JOIN concentrado_informacion Cinf ON Cinf.ID_EVALUACION = EV.ID_EVALUACION
			WHERE Cin.FECHA_RI BETWEEN '$FECHA1' AND '$FECHA2' AND EV.ID_EVALUACION NOT IN (SELECT EV1.EVALUACION_DERIVADA_DE FROM evaluacion EV1 WHERE EV1.EVALUACION_DERIVADA_DE LIKE '%_%' AND EV1.FECHA_EVALUACION BETWEEN '$FECHA1' AND '$FECHA2') AND EV.FOLIO!='' AND EV.FOLIO!='-' AND EV.FOLIO IS NOT NULL".$lol)) {

		while($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $myArray[] = $row;
    	}
    	echo json_encode($myArray,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    	$result -> close();

    }


$conexion -> close();
?>