<?php
header("Content-type: text/html; charset=utf8");
header('Content-type:application/json');
require("../../conexion.php"); 

$FECHA1 = $_REQUEST['FECHA1'];
$FECHA2 = $_REQUEST['FECHA2'];
$lol = $_REQUEST['lol'];


$conexion->set_charset("utf8");


	if($lol == "total" || $lol ==""){
		if ($result = $conexion->query("SELECT COUNT(*) AS cantidad FROM evaluacion EV WHERE EV.FECHA_EVALUACION BETWEEN '$FECHA1' AND '$FECHA2' AND EV.EVALUACION_DERIVADA_DE NOT LIKE '%_%'")) {

			while($row = $result->fetch_array(MYSQLI_ASSOC)) {
	            $myArray[] = $row;
	    	}
	    	echo json_encode($myArray,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
	    	$result -> close();
	    }
	}
	else{
		if ($result = $conexion->query("SELECT COUNT(*) AS cantidad FROM evaluacion EV LEFT JOIN candidatos CA ON CA.ID_CANDIDATO = EV.ID_CANDIDATO LEFT JOIN oficios O ON O.ID_CANDIDATO = EV.ID_CANDIDATO AND O.ID_EVALUACION = EV.ID_EVALUACION 
		LEFT JOIN medico_clinica01 M01 ON M01.ID_CANDIDATO = EV.ID_CANDIDATO AND M01.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica03 M03 ON M03.ID_CANDIDATO = EV.ID_CANDIDATO AND M03.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica04 M04 ON M04.ID_CANDIDATO = EV.ID_CANDIDATO AND M04.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica05 M05 ON M05.ID_CANDIDATO = EV.ID_CANDIDATO AND M05.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica06 M06 ON M06.ID_CANDIDATO = EV.ID_CANDIDATO AND M06.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica07 M07 ON M07.ID_CANDIDATO = EV.ID_CANDIDATO AND M07.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica08 M08 ON M08.ID_CANDIDATO = EV.ID_CANDIDATO AND M08.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica09 M09 ON M09.ID_CANDIDATO = EV.ID_CANDIDATO AND M09.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica10 M10 ON M10.ID_CANDIDATO = EV.ID_CANDIDATO AND M10.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica11 M11 ON M11.ID_CANDIDATO = EV.ID_CANDIDATO AND M11.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica12 M12 ON M12.ID_CANDIDATO = EV.ID_CANDIDATO AND M12.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN medico_clinica13 M13 ON M13.ID_CANDIDATO = EV.ID_CANDIDATO AND M13.ID_EVALUACION = EV.ID_EVALUACION LEFT JOIN reportes_med R ON R.ID_EVALUACION = EV.ID_EVALUACION WHERE EV.FECHA_EVALUACION BETWEEN '$FECHA1' AND '$FECHA2' AND EV.EVALUACION_DERIVADA_DE NOT LIKE '%_%'".$lol)) {

			while($row = $result->fetch_array(MYSQLI_ASSOC)) {
	            $myArray[] = $row;
	    	}
	    	echo json_encode($myArray,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
	    	$result -> close();
	    }
	}


$conexion -> close();
?>