<?php
header("Content-type: text/html; charset=utf8");
include ("../MySqlConnect.php");
include ("../conection.php");
$TIPO_BUSQUEDA = $_POST['MODO'];
$PARAM = $_POST['SEARCH_DATA'];
$query = "";
switch ((int)$TIPO_BUSQUEDA)
{
	case 0:
	// Folio
    $query = sprintf("SELECT O.NUM_OFICIO, O.DEPENDENCIA, O.CORPORACION, O.ADSCRIPCION, O.PUESTO, E.ID_EVALUACION, E.FOLIO, E.FECHA_EVALUACION, C.PRIMER_APELLIDO, 
	C.SEGUNDO_APELLIDO, C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, E.TIPO_EVALUACION, E.MOTIVO_EVALUACION, E.MODO_EVALUACION, E.ORIGEN_DE_RECURSOS, E.SOLICITANTE_DE_EVALUACION, 
	E.FECHA_EXAMEN_TOXICOLOGICO, E.FECHA_ISE_DOCUMENTOS, E.FECHA_ISE_ENTREVISTA, E.FECHA_EXAMEN_PSICOLOGICO, E.FECHA_EXAMEN_MEDICO, E.FECHA_EXAMEN_POLIGRAFICO, 
	(SELECT FECHA_EXAMEN_POLIGRAFICO FROM EVALUACION WHERE EVALUACION_DERIVADA_DE LIKE E.ID_EVALUACION) AS REEX, 
	(SELECT CONCAT (FECHA, '+', FECHA_CORPORACION) AS FECHAS_OFICIOS FROM NOTIFICACION_INFORMACION WHERE ID_RESULTADO LIKE 
	(SELECT ID_RESULTADO FROM NOTIFICACION_EXPEDIENTE WHERE ID_EXPEDIENTE LIKE 
	(SELECT ID_EXPEDIENTE FROM EXPEDIENTE_INFORMACION WHERE ID_EVALUACION LIKE E.ID_EVALUACION))) AS FECHAS_OFICIOS 
	FROM OFICIOS O 
	LEFT JOIN EVALUACION E ON (O.ID_EVALUACION = E.ID_EVALUACION) 
	INNER JOIN CANDIDATOS C ON (O.ID_CANDIDATO = C.ID_CANDIDATO) 
	WHERE O.NUM_OFICIO LIKE (SELECT NUM_OFICIO FROM OFICIOS WHERE ID_EVALUACION LIKE (SELECT ID_EVALUACION FROM EVALUACION WHERE FOLIO LIKE '%s')) AND E.FOLIO LIKE '%s';", $PARAM, $PARAM); 
	break;
	case 1:
	// Oficio
	$query = sprintf("SELECT O.NUM_OFICIO, O.DEPENDENCIA, O.CORPORACION, O.ADSCRIPCION, O.PUESTO, E.ID_EVALUACION, E.FOLIO, E.FECHA_EVALUACION, C.PRIMER_APELLIDO, 
	C.SEGUNDO_APELLIDO, C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, E.TIPO_EVALUACION, E.MOTIVO_EVALUACION, E.MODO_EVALUACION, E.ORIGEN_DE_RECURSOS, E.SOLICITANTE_DE_EVALUACION, 
	E.FECHA_EXAMEN_TOXICOLOGICO, E.FECHA_ISE_DOCUMENTOS, E.FECHA_ISE_ENTREVISTA, E.FECHA_EXAMEN_PSICOLOGICO, E.FECHA_EXAMEN_MEDICO, E.FECHA_EXAMEN_POLIGRAFICO, 
	(SELECT FECHA_EXAMEN_POLIGRAFICO FROM EVALUACION WHERE EVALUACION_DERIVADA_DE LIKE E.ID_EVALUACION) AS REEX, 
	(SELECT CONCAT (FECHA, '+', FECHA_CORPORACION) AS FECHAS_OFICIOS FROM NOTIFICACION_INFORMACION WHERE ID_RESULTADO LIKE 
	(SELECT ID_RESULTADO FROM NOTIFICACION_EXPEDIENTE WHERE ID_EXPEDIENTE LIKE 
	(SELECT ID_EXPEDIENTE FROM EXPEDIENTE_INFORMACION WHERE ID_EVALUACION LIKE E.ID_EVALUACION))) AS FECHAS_OFICIOS 
	FROM OFICIOS O 
	LEFT JOIN EVALUACION E ON (O.ID_EVALUACION = E.ID_EVALUACION) 
	INNER JOIN CANDIDATOS C ON (O.ID_CANDIDATO = C.ID_CANDIDATO) 
	WHERE O.NUM_OFICIO LIKE '%s';", $PARAM); 
	break;
	case 2:
	// Fecha alta de evaluación
	$query = sprintf("SELECT O.NUM_OFICIO, O.DEPENDENCIA, O.CORPORACION, O.ADSCRIPCION, O.PUESTO, E.ID_EVALUACION, E.FOLIO, E.FECHA_EVALUACION, C.PRIMER_APELLIDO, 
	C.SEGUNDO_APELLIDO, C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, E.TIPO_EVALUACION, E.MOTIVO_EVALUACION, E.MODO_EVALUACION, E.ORIGEN_DE_RECURSOS, E.SOLICITANTE_DE_EVALUACION, 
	E.FECHA_EXAMEN_TOXICOLOGICO, E.FECHA_ISE_DOCUMENTOS, E.FECHA_ISE_ENTREVISTA, E.FECHA_EXAMEN_PSICOLOGICO, E.FECHA_EXAMEN_MEDICO, E.FECHA_EXAMEN_POLIGRAFICO, 
	(SELECT FECHA_EXAMEN_POLIGRAFICO FROM EVALUACION WHERE EVALUACION_DERIVADA_DE LIKE E.ID_EVALUACION) AS REEX, 
	(SELECT CONCAT (FECHA, '+', FECHA_CORPORACION) AS FECHAS_OFICIOS FROM NOTIFICACION_INFORMACION WHERE ID_RESULTADO LIKE 
	(SELECT ID_RESULTADO FROM NOTIFICACION_EXPEDIENTE WHERE ID_EXPEDIENTE LIKE 
	(SELECT ID_EXPEDIENTE FROM EXPEDIENTE_INFORMACION WHERE ID_EVALUACION LIKE E.ID_EVALUACION))) AS FECHAS_OFICIOS 
	FROM EVALUACION E 
	RIGHT JOIN OFICIOS O ON (E.ID_EVALUACION = O.ID_EVALUACION) 
	INNER JOIN CANDIDATOS C ON (E.ID_CANDIDATO = C.ID_CANDIDATO) 
	WHERE E.FECHA_EVALUACION LIKE '%s';", $PARAM); 
	break;
	case 3:
	// Fecha de evaluación (Tox)
	$query = sprintf("SELECT O.NUM_OFICIO, O.DEPENDENCIA, O.CORPORACION, O.ADSCRIPCION, O.PUESTO, E.ID_EVALUACION, E.FOLIO, E.FECHA_EVALUACION, C.PRIMER_APELLIDO, 
	C.SEGUNDO_APELLIDO, C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, E.TIPO_EVALUACION, E.MOTIVO_EVALUACION, E.MODO_EVALUACION, E.ORIGEN_DE_RECURSOS, E.SOLICITANTE_DE_EVALUACION, 
	E.FECHA_EXAMEN_TOXICOLOGICO, E.FECHA_ISE_DOCUMENTOS, E.FECHA_ISE_ENTREVISTA, E.FECHA_EXAMEN_PSICOLOGICO, E.FECHA_EXAMEN_MEDICO, E.FECHA_EXAMEN_POLIGRAFICO, 
	(SELECT FECHA_EXAMEN_POLIGRAFICO FROM EVALUACION WHERE EVALUACION_DERIVADA_DE LIKE E.ID_EVALUACION) AS REEX, 
	(SELECT CONCAT (FECHA, '+', FECHA_CORPORACION) AS FECHAS_OFICIOS FROM NOTIFICACION_INFORMACION WHERE ID_RESULTADO LIKE 
	(SELECT ID_RESULTADO FROM NOTIFICACION_EXPEDIENTE WHERE ID_EXPEDIENTE LIKE 
	(SELECT ID_EXPEDIENTE FROM EXPEDIENTE_INFORMACION WHERE ID_EVALUACION LIKE E.ID_EVALUACION))) AS FECHAS_OFICIOS 
	FROM OFICIOS O 
	LEFT JOIN EVALUACION E ON (O.ID_EVALUACION = E.ID_EVALUACION) 
	INNER JOIN CANDIDATOS C ON (E.ID_CANDIDATO = C.ID_CANDIDATO) 
	WHERE E.FECHA_EXAMEN_TOXICOLOGICO LIKE '%s%%'", $PARAM); 
	break;
	case 4:
	// Nombre
	$nombre = "%".str_replace(' ', '%', $PARAM)."%";
	$query = sprintf("SELECT O.NUM_OFICIO, O.DEPENDENCIA, O.CORPORACION, O.ADSCRIPCION, O.PUESTO, E.ID_EVALUACION, E.FOLIO, E.FECHA_EVALUACION, C.PRIMER_APELLIDO, 
	C.SEGUNDO_APELLIDO, C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, E.TIPO_EVALUACION, E.MOTIVO_EVALUACION, E.MODO_EVALUACION, E.ORIGEN_DE_RECURSOS, E.SOLICITANTE_DE_EVALUACION, 
	E.FECHA_EXAMEN_TOXICOLOGICO, E.FECHA_ISE_DOCUMENTOS, E.FECHA_ISE_ENTREVISTA, E.FECHA_EXAMEN_PSICOLOGICO, E.FECHA_EXAMEN_MEDICO, E.FECHA_EXAMEN_POLIGRAFICO, 
	(SELECT FECHA_EXAMEN_POLIGRAFICO FROM EVALUACION WHERE EVALUACION_DERIVADA_DE LIKE E.ID_EVALUACION) AS REEX, 
	(SELECT CONCAT (FECHA, '+', FECHA_CORPORACION) AS FECHAS_OFICIOS FROM NOTIFICACION_INFORMACION WHERE ID_RESULTADO LIKE 
	(SELECT ID_RESULTADO FROM NOTIFICACION_EXPEDIENTE WHERE ID_EXPEDIENTE LIKE 
	(SELECT ID_EXPEDIENTE FROM EXPEDIENTE_INFORMACION WHERE ID_EVALUACION LIKE E.ID_EVALUACION))) AS FECHAS_OFICIOS 
	FROM OFICIOS O 
	LEFT JOIN EVALUACION E ON (O.ID_EVALUACION = E.ID_EVALUACION) 
	INNER JOIN CANDIDATOS C ON (O.ID_CANDIDATO = C.ID_CANDIDATO) 
	WHERE CONCAT(C.PRIMER_NOMBRE, ' ', C.SEGUNDO_NOMBRE, ' ', C.PRIMER_APELLIDO, ' ', C.SEGUNDO_APELLIDO) LIKE '%s';", $nombre);
	break;
}
$conexion = new MySqlConnect($db, $user, $pswd); 
$conexion->executeSelectQuery($query, TRUE);
$conexion->closeMySqlConnection();
?>