<?php
header("Content-type: text/html; charset=utf8");
header('Content-type:application/json');
require("../conexion.php"); 

 
$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];


$conexion->set_charset("utf8");



	if ($result = $conexion->query("SELECT E.ESTADO_CIVIL,E2.CALLE AS DOMICILIO,E2.NO_EXTERIOR AS NUMERO,E2.COLONIA,E2.DELEGACION AS MUNICIPIO,E.RFC,E.LUGAR_NACIMIENTO,E.NUMERO_CASA,E.NUMERO_CELULAR,E3.ESTUDIOS AS ULTIMO_GRADO_ESTUDIOS,P.PUESTO_FUNCIONAL,R.*,H.*,D.*,O.*,EE.* 
	FROM digiscan H LEFT JOIN oficios O ON H.ID_CANDIDATO = O.ID_CANDIDATO AND H.ID_EVALUACION = O.ID_EVALUACION 
	LEFT JOIN psicologia_reporte P ON H.ID_CANDIDATO = P.ID_CANDIDATO AND H.ID_EVALUACION = P.ID_EVALUACION 
	LEFT JOIN reporte_ise R ON H.ID_CANDIDATO = R.ID_CANDIDATO AND H.ID_EVALUACION = R.ID_EVALUACION 
	LEFT JOIN entrevista D ON H.ID_CANDIDATO = D.ID_CANDIDATO AND H.ID_EVALUACION = D.ID_EVALUACION 
	LEFT JOIN historia_1 E ON H.ID_EVALUACION = E.ID_EVALUACION 
	LEFT JOIN historia_31 E2 ON H.ID_EVALUACION = E2.ID_EVALUACION 
	LEFT JOIN historia_5 E3 ON H.ID_EVALUACION = E3.ID_EVALUACION 
	LEFT JOIN evaluador_evaluacion EE ON H.ID_EVALUACION = EE.ID_EVALUACION 
	WHERE H.ID_CANDIDATO = '$ID_CANDIDATO' AND H.ID_EVALUACION = '$ID_EVALUACION' and EE.DEPARTAMENTO = 'ISE'")) {

		while($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $myArray[] = $row;
    	}
    	echo json_encode($myArray,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    	$result -> close();

    }


$conexion -> close();
?>