<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$EMPRESA1 = $_POST['EMPRESA1'];
$PUESTO1 = $_POST['PUESTO1'];
$ANTIGUEDAD1 = $_POST['ANTIGUEDAD1'];
$CAUSA_SEPARACION1 = $_POST['CAUSA_SEPARACION1'];
$EMPRESA2 = $_POST['EMPRESA2'];
$PUESTO2 = $_POST['PUESTO2'];
$ANTIGUEDAD2 = $_POST['ANTIGUEDAD2'];
$CAUSA_SEPARACION2 = $_POST['CAUSA_SEPARACION2'];
$EMPRESA3 = $_POST['EMPRESA3'];
$PUESTO3 = $_POST['PUESTO3'];
$ANTIGUEDAD3 = $_POST['ANTIGUEDAD3'];
$CAUSA_SEPARACION3 = $_POST['CAUSA_SEPARACION3'];
$EMPRESA4 = $_POST['EMPRESA4'];
$PUESTO4 = $_POST['PUESTO4'];
$ANTIGUEDAD4 = $_POST['ANTIGUEDAD4'];
$CAUSA_SEPARACION4 = $_POST['CAUSA_SEPARACION4'];
$EMPRESA5 = $_POST['EMPRESA5'];
$PUESTO5 = $_POST['PUESTO5'];
$ANTIGUEDAD5 = $_POST['ANTIGUEDAD5'];
$CAUSA_SEPARACION5 = $_POST['CAUSA_SEPARACION5'];





/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica02($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			
			$sqlUpdate = "UPDATE medico_clinica02 SET EMPRESA1 = '$EMPRESA1', PUESTO1 = '$PUESTO1', ANTIGUEDAD1 = '$ANTIGUEDAD1', CAUSA_SEPARACION1 = '$CAUSA_SEPARACION1',EMPRESA2  = '$EMPRESA2', PUESTO2 = '$PUESTO2',ANTIGUEDAD2='$ANTIGUEDAD2',CAUSA_SEPARACION2='$CAUSA_SEPARACION2',EMPRESA3='$EMPRESA3',PUESTO3='$PUESTO3',ANTIGUEDAD3='$ANTIGUEDAD3',CAUSA_SEPARACION3='$CAUSA_SEPARACION3',EMPRESA4='$EMPRESA4',PUESTO4='$PUESTO4',ANTIGUEDAD4='$ANTIGUEDAD4',CAUSA_SEPARACION4='$CAUSA_SEPARACION4',EMPRESA5='$EMPRESA5',PUESTO5='$PUESTO5',ANTIGUEDAD5='$ANTIGUEDAD5',CAUSA_SEPARACION5='$CAUSA_SEPARACION5' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION = '$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica02 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$EMPRESA1', '$PUESTO1', '$ANTIGUEDAD1','$CAUSA_SEPARACION1' ,'$EMPRESA2', '$PUESTO2', '$ANTIGUEDAD2', '$CAUSA_SEPARACION2', '$EMPRESA3', '$PUESTO3', '$ANTIGUEDAD3', '$CAUSA_SEPARACION3', '$EMPRESA4', '$PUESTO4', '$ANTIGUEDAD4', '$CAUSA_SEPARACION4', '$EMPRESA5', '$PUESTO5', '$ANTIGUEDAD5', '$CAUSA_SEPARACION5')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>