<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$SISTEMA_NEUROSENSORIAL = $_POST['SISTEMA_NEUROSENSORIAL'];
$SISTEMA_NEUROSENSORIAL_OTRAS = $_POST['SISTEMA_NEUROSENSORIAL_OTRAS'];
$RESPIRATORIO = $_POST['RESPIRATORIO'];
$RESPIRATORIO_OTRAS = $_POST['RESPIRATORIO_OTRAS'];
$CARDIOVASCULAR = $_POST['CARDIOVASCULAR'];
$CARDIOVASCULAR_OTRAS = $_POST['CARDIOVASCULAR_OTRAS'];
$ENDOCRINOLOGICO = $_POST['ENDOCRINOLOGICO'];
$ENDOCRINOLOGICO_OTRAS = $_POST['ENDOCRINOLOGICO_OTRAS'];
$DIGESTIVO = $_POST['DIGESTIVO'];
$DIGESTIVO_OTRAS = $_POST['DIGESTIVO_OTRAS'];
$GENITOURINARIO = $_POST['GENITOURINARIO'];
$GENITOURINARIO_OTRAS = $_POST['GENITOURINARIO_OTRAS'];
$HEMATOLOGICO = $_POST['HEMATOLOGICO'];
$HEMATOLOGICO_OTRAS = $_POST['HEMATOLOGICO_OTRAS'];
$OSTEOMUSCULAR = $_POST['OSTEOMUSCULAR'];
$OSTEOMUSCULAR_OTRAS = $_POST['OSTEOMUSCULAR_OTRAS'];


/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica11($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica11 SET SISTEMA_NEUROSENSORIAL = '$SISTEMA_NEUROSENSORIAL', SISTEMA_NEUROSENSORIAL_OTRAS = '$SISTEMA_NEUROSENSORIAL_OTRAS', RESPIRATORIO = '$RESPIRATORIO', RESPIRATORIO_OTRAS = '$RESPIRATORIO_OTRAS', CARDIOVASCULAR = '$CARDIOVASCULAR', CARDIOVASCULAR_OTRAS = '$CARDIOVASCULAR_OTRAS',ENDOCRINOLOGICO='$ENDOCRINOLOGICO',ENDOCRINOLOGICO_OTRAS='$ENDOCRINOLOGICO_OTRAS',DIGESTIVO='$DIGESTIVO',DIGESTIVO_OTRAS='$DIGESTIVO_OTRAS',GENITOURINARIO='$GENITOURINARIO',GENITOURINARIO_OTRAS='$GENITOURINARIO_OTRAS',HEMATOLOGICO='$HEMATOLOGICO',HEMATOLOGICO_OTRAS='$HEMATOLOGICO_OTRAS',OSTEOMUSCULAR='$OSTEOMUSCULAR',OSTEOMUSCULAR_OTRAS='$OSTEOMUSCULAR_OTRAS' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica11 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$SISTEMA_NEUROSENSORIAL', '$SISTEMA_NEUROSENSORIAL_OTRAS', '$RESPIRATORIO','$RESPIRATORIO_OTRAS' ,'$CARDIOVASCULAR', '$CARDIOVASCULAR_OTRAS', '$ENDOCRINOLOGICO', '$ENDOCRINOLOGICO_OTRAS', '$DIGESTIVO', '$DIGESTIVO_OTRAS', '$GENITOURINARIO', '$GENITOURINARIO_OTRAS', '$HEMATOLOGICO', '$HEMATOLOGICO_OTRAS', '$OSTEOMUSCULAR', '$OSTEOMUSCULAR_OTRAS')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>