<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$DIABETES = $_POST['DIABETES'];
$HIPERTENSION = $_POST['HIPERTENSION'];
$CANCER = $_POST['CANCER'];
$EVENTOS_VASCULARES = $_POST['EVENTOS_VASCULARES'];
$ASMA = $_POST['ASMA'];
$INFARTOS = $_POST['INFARTOS'];
$ARTRITIS = $_POST['ARTRITIS'];
$LUPUS = $_POST['LUPUS'];
$TUBERCULOSIS = $_POST['TUBERCULOSIS'];
$EPILEPSIA = $_POST['EPILEPSIA'];
$INSF_RENAL = $_POST['INSF_RENAL'];
$INSF_HEPATICA = $_POST['INSF_HEPATICA'];
$SIFILIS = $_POST['SIFILIS'];
$TIROIDOPATIAS = $_POST['TIROIDOPATIAS'];
$ENFS_SANGRE = $_POST['ENFS_SANGRE'];
$ENFS_MENTE = $_POST['ENFS_MENTE'];
$ABUELO_P = $_POST['ABUELO_P'];
$ABUELA_P = $_POST['ABUELA_P'];
$ABUELO_M = $_POST['ABUELO_M'];
$ABUELA_M = $_POST['ABUELA_M'];
$PADRE = $_POST['PADRE'];
$MADRE = $_POST['MADRE'];
$HERMANO = $_POST['HERMANO'];
$RELIGION = $_POST['RELIGION'];
$VIVE = $_POST['VIVE'];
$ESCOLARIDAD = $_POST['ESCOLARIDAD'];
$LEER = $_POST['LEER'];
$HIJO = $_POST['HIJO'];



/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica01($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica01 SET DIABETES = '$DIABETES', HIPERTENSION = '$HIPERTENSION', CANCER = '$CANCER', EVENTOS_VASCULARES = '$EVENTOS_VASCULARES', ASMA = '$ASMA', INFARTOS = '$INFARTOS',ARTRITIS='$ARTRITIS',LUPUS='$LUPUS',TUBERCULOSIS='$TUBERCULOSIS',EPILEPSIA='$EPILEPSIA',INSF_RENAL='$INSF_RENAL',INSF_HEPATICA='$INSF_HEPATICA',SIFILIS='$SIFILIS',TIROIDOPATIAS='$TIROIDOPATIAS',ENFS_SANGRE='$ENFS_SANGRE',ENFS_MENTE='$ENFS_MENTE',ABUELO_P='$ABUELO_P',ABUELA_P='$ABUELA_P',ABUELO_M='$ABUELO_M',ABUELA_M='$ABUELA_M',PADRE='$PADRE',MADRE='$MADRE',HERMANO='$HERMANO',HIJO='$HIJO',RELIGION='$RELIGION',VIVE='$VIVE',ESCOLARIDAD='$ESCOLARIDAD',LEER='$LEER' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica01 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$DIABETES', '$HIPERTENSION', '$CANCER','$EVENTOS_VASCULARES' ,'$ASMA', '$INFARTOS', '$ARTRITIS', '$LUPUS', '$TUBERCULOSIS', '$EPILEPSIA', '$INSF_RENAL', '$INSF_HEPATICA', '$SIFILIS', '$TIROIDOPATIAS', '$ENFS_SANGRE', '$ENFS_MENTE', '$ABUELO_P', '$ABUELA_P', '$ABUELO_M', '$ABUELA_M', '$PADRE', '$MADRE', '$HERMANO', '$HIJO', '$RELIGION', '$VIVE', '$ESCOLARIDAD', '$LEER')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>