<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$EXPLORACION_OIDOS = $_POST['EXPLORACION_OIDOS'];
$OBSERVACIONES_OIDOS = $_POST['OBSERVACIONES_OIDOS'];
$MUCOSA = $_POST['MUCOSA'];
$LENGUA = $_POST['LENGUA'];
$DIENTES = $_POST['DIENTES'];
$PALADAR = $_POST['PALADAR'];
$UVULA = $_POST['UVULA'];
$HIGIENE = $_POST['HIGIENE'];
$TONO = $_POST['TONO'];
$AUSENCIAS_DENTALES = $_POST['AUSENCIAS_DENTALES'];
$CAUSAS_AD = $_POST['CAUSAS_AD'];
$OBSERVACIONES_BOCA = $_POST['OBSERVACIONES_BOCA'];
$FORMA = $_POST['FORMA'];
$PULSO = $_POST['PULSO'];
$MOVIMIENTOS = $_POST['MOVIMIENTOS'];
$TONO_CUELLO = $_POST['TONO_CUELLO'];
$GANGLIS = $_POST['GANGLIS'];
$GANGLIS_T = $_POST['GANGLIS_T'];
$OBSERVACIONES_CUELLO = $_POST['OBSERVACIONES_CUELLO'];


/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica12($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica12 SET EXPLORACION_OIDOS = '$EXPLORACION_OIDOS', OBSERVACIONES_OIDOS = '$OBSERVACIONES_OIDOS', MUCOSA = '$MUCOSA', LENGUA = '$LENGUA', DIENTES = '$DIENTES', PALADAR = '$PALADAR',UVULA='$UVULA',HIGIENE='$HIGIENE',TONO='$TONO',AUSENCIAS_DENTALES='$AUSENCIAS_DENTALES',CAUSAS_AD='$CAUSAS_AD',OBSERVACIONES_BOCA='$OBSERVACIONES_BOCA',FORMA='$FORMA',PULSO='$PULSO',MOVIMIENTOS='$MOVIMIENTOS',TONO_CUELLO='$TONO_CUELLO',GANGLIS='$GANGLIS',GANGLIS_T='$GANGLIS_T',OBSERVACIONES_CUELLO='$OBSERVACIONES_CUELLO' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica12 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$EXPLORACION_OIDOS', '$OBSERVACIONES_OIDOS', '$MUCOSA','$LENGUA' ,'$DIENTES', '$PALADAR', '$UVULA', '$HIGIENE', '$TONO', '$AUSENCIAS_DENTALES', '$CAUSAS_AD', '$OBSERVACIONES_BOCA', '$FORMA', '$PULSO', '$MOVIMIENTOS', '$TONO_CUELLO', '$GANGLIS', '$GANGLIS_T', '$OBSERVACIONES_CUELLO')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>