<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$TIPO_RESPIRATORIO = $_POST['TIPO_RESPIRATORIO'];
$PALPACION = $_POST['PALPACION'];
$SOPLOS = $_POST['SOPLOS'];
$DESCRIPCION_CARDIO = $_POST['DESCRIPCION_CARDIO'];
$OBSERVACIONES_CARDIO = $_POST['OBSERVACIONES_CARDIO'];
$TIPO_ABDOMEN = $_POST['TIPO_ABDOMEN'];
$PERISTASIS = $_POST['PERISTASIS'];
$VICEROMEGA = $_POST['VICEROMEGA'];
$PUNTOS_DOLOR = $_POST['PUNTOS_DOLOR'];
$ADENOMEGA = $_POST['ADENOMEGA'];
$HERNIAS = $_POST['HERNIAS'];
$OBSERVACIONES_DIGESTIVO = $_POST['OBSERVACIONES_DIGESTIVO'];
$OBSERVACIONES_ENDOCRINO = $_POST['OBSERVACIONES_ENDOCRINO'];
$GIORDANO = $_POST['GIORDANO'];
$PUNTOS = $_POST['PUNTOS'];
$OBSERVACIONES_GENI = $_POST['OBSERVACIONES_GENI'];


/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica13($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica13 SET TIPO_RESPIRATORIO = '$TIPO_RESPIRATORIO', PALPACION = '$PALPACION', SOPLOS = '$SOPLOS', DESCRIPCION_CARDIO = '$DESCRIPCION_CARDIO', OBSERVACIONES_CARDIO = '$OBSERVACIONES_CARDIO', TIPO_ABDOMEN = '$TIPO_ABDOMEN',PERISTASIS='$PERISTASIS',VICEROMEGA='$VICEROMEGA',PUNTOS_DOLOR='$PUNTOS_DOLOR',ADENOMEGA='$ADENOMEGA',HERNIAS='$HERNIAS',OBSERVACIONES_DIGESTIVO='$OBSERVACIONES_DIGESTIVO',OBSERVACIONES_ENDOCRINO='$OBSERVACIONES_ENDOCRINO',GIORDANO='$GIORDANO',PUNTOS='$PUNTOS',OBSERVACIONES_GENI='$OBSERVACIONES_GENI' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica13 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$TIPO_RESPIRATORIO', '$PALPACION', '$SOPLOS','$DESCRIPCION_CARDIO' ,'$OBSERVACIONES_CARDIO', '$TIPO_ABDOMEN', '$PERISTASIS', '$VICEROMEGA', '$PUNTOS_DOLOR', '$ADENOMEGA', '$HERNIAS', '$OBSERVACIONES_DIGESTIVO', '$OBSERVACIONES_ENDOCRINO', '$GIORDANO', '$PUNTOS', '$OBSERVACIONES_GENI')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>