<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$BIOMETRIA = $_POST['BIOMETRIA'];
$QUIMICA_SANGUINEA = $_POST['QUIMICA_SANGUINEA'];
$EXAMEN_ORINA = $_POST['EXAMEN_ORINA'];
$OTRAS_B = $_POST['OTRAS_B'];
$OTRAS_Q = $_POST['OTRAS_Q'];
$OTRAS_E = $_POST['OTRAS_E'];
$GRUPO_SANGUINEO = $_POST['GRUPO_SANGUINEO'];
$RAYOS_X = $_POST['RAYOS_X'];
$DIAGNOSTICO = $_POST['DIAGNOSTICO'];
$RECOMENDACIONES = $_POST['RECOMENDACIONES'];
$CEDULA = $_POST['CEDULA'];
$EDAD = $_POST['EDAD'];
$NACIMIENTO = $_POST['NACIMIENTO'];
$DOMICILIO = $_POST['DOMICILIO'];
$TELEFONO = $_POST['TELEFONO'];
$OCUPACION = $_POST['OCUPACION'];
$PUESTO = $_POST['PUESTO'];
$ANTIGUEDAD = $_POST['ANTIGUEDAD'];
$IDENTIFICACION = $_POST['IDENTIFICACION'];
$ESTADO_CIVIL = $_POST['ESTADO_CIVIL'];



/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica15($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica15 SET BIOMETRIA = '$BIOMETRIA',QUIMICA_SANGUINEA = '$QUIMICA_SANGUINEA', EXAMEN_ORINA = '$EXAMEN_ORINA', OTRAS_B = '$OTRAS_B', OTRAS_Q = '$OTRAS_Q', OTRAS_E = '$OTRAS_E', GRUPO_SANGUINEO = '$GRUPO_SANGUINEO', RAYOS_X = '$RAYOS_X',DIAGNOSTICO='$DIAGNOSTICO',RECOMENDACIONES='$RECOMENDACIONES',CEDULA='$CEDULA',EDAD='$EDAD',NACIMIENTO='$NACIMIENTO',DOMICILIO='$DOMICILIO',TELEFONO='$TELEFONO',OCUPACION='$OCUPACION',PUESTO='$PUESTO',ANTIGUEDAD='$ANTIGUEDAD',IDENTIFICACION='$IDENTIFICACION',ESTADO_CIVIL='$ESTADO_CIVIL' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica15 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$BIOMETRIA','$QUIMICA_SANGUINEA', '$EXAMEN_ORINA', '$OTRAS_B', '$OTRAS_Q','$OTRAS_E' ,'$GRUPO_SANGUINEO', '$RAYOS_X', '$DIAGNOSTICO', '$RECOMENDACIONES', '$CEDULA', '$EDAD', '$NACIMIENTO', '$DOMICILIO', '$TELEFONO', '$OCUPACION', '$PUESTO', '$ANTIGUEDAD', '$IDENTIFICACION', '$ESTADO_CIVIL')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>