<?php
header("Content-type: text/html; charset=utf8");
require("../../../conexion.php");
include_once "../ConexionBD.php"; 

$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];
$INTEGRIDAD = $_POST['INTEGRIDAD'];
$SIMETRICAS = $_POST['SIMETRICAS'];
$MOVIMIENTOS_COLUMNA = $_POST['MOVIMIENTOS_COLUMNA'];
$TONO_MUSCULAR_COLUMNA = $_POST['TONO_MUSCULAR_COLUMNA'];
$SENSIBILIDAD = $_POST['SENSIBILIDAD'];
$PULSOS = $_POST['PULSOS'];
$ROT = $_POST['ROT'];
$LLENADO_CAPILAR = $_POST['LLENADO_CAPILAR'];
$PIE_PLANO = $_POST['PIE_PLANO'];
$DOLOR_COLUMNA = $_POST['DOLOR_COLUMNA'];
$OBSERVACIONES_COLUMNA = $_POST['OBSERVACIONES_COLUMNA'];
$CALCULO = $_POST['CALCULO'];
$JUICIO = $_POST['JUICIO'];
$FLUIDEZ_IDEAS = $_POST['FLUIDEZ_IDEAS'];
$PRECISION_TIEMPO = $_POST['PRECISION_TIEMPO'];
$PRECISION_ESPACIO = $_POST['PRECISION_ESPACIO'];
$ALTERACIONES = $_POST['ALTERACIONES'];
$PARESTESIAS = $_POST['PARESTESIAS'];
$OBSERVACIONES_NEUROLOGICO = $_POST['OBSERVACIONES_NEUROLOGICO'];


/*"INSERT INTO ASISTENCIA VALUES ('$ID_CANDIDATO', '$ID_EVALUACION', '$NOMBRE','$PRUEBA' ,'$FECHA', '$ASISTENCIA')"*/
		$cone = conectarBD();
		$lol = Verificar_clinica14($cone,$ID_CANDIDATO, $ID_EVALUACION);
		echo $lol;
		$conexion->set_charset("utf8");

		if($lol=="correcto"){
			$sqlUpdate = "UPDATE medico_clinica14 SET INTEGRIDAD = '$INTEGRIDAD', SIMETRICAS = '$SIMETRICAS', MOVIMIENTOS_COLUMNA = '$MOVIMIENTOS_COLUMNA', TONO_MUSCULAR_COLUMNA = '$TONO_MUSCULAR_COLUMNA', SENSIBILIDAD = '$SENSIBILIDAD', PULSOS = '$PULSOS', ROT = '$ROT',LLENADO_CAPILAR='$LLENADO_CAPILAR',PIE_PLANO='$PIE_PLANO',DOLOR_COLUMNA='$DOLOR_COLUMNA',OBSERVACIONES_COLUMNA='$OBSERVACIONES_COLUMNA',CALCULO='$CALCULO',JUICIO='$JUICIO',FLUIDEZ_IDEAS='$FLUIDEZ_IDEAS',PRECISION_TIEMPO='$PRECISION_TIEMPO',PRECISION_ESPACIO='$PRECISION_ESPACIO',ALTERACIONES='$ALTERACIONES',PARESTESIAS='$PARESTESIAS',OBSERVACIONES_NEUROLOGICO='$OBSERVACIONES_NEUROLOGICO' WHERE ID_CANDIDATO = '$ID_CANDIDATO' AND ID_EVALUACION ='$ID_EVALUACION'";
			if ($conexion->query($sqlUpdate) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
			
		}

		else{
			$sqlInsert = "INSERT INTO medico_clinica14 VALUES ('$ID_CANDIDATO','$ID_EVALUACION','$INTEGRIDAD', '$SIMETRICAS', '$MOVIMIENTOS_COLUMNA', '$TONO_MUSCULAR_COLUMNA','$SENSIBILIDAD' ,'$PULSOS', '$ROT', '$LLENADO_CAPILAR', '$PIE_PLANO', '$DOLOR_COLUMNA', '$OBSERVACIONES_COLUMNA', '$CALCULO', '$JUICIO', '$FLUIDEZ_IDEAS', '$PRECISION_TIEMPO', '$PRECISION_ESPACIO', '$ALTERACIONES', '$PARESTESIAS', '$OBSERVACIONES_NEUROLOGICO')";

			if ($conexion->query($sqlInsert) === TRUE) {
		   	 	echo "true";
			} 
				else {
		    	echo "false";
					 }
		}
		

$conexion->close();

?>