<?php
header("Content-type: text/html; charset=utf8");
header('Content-type:application/json');
require("../../../conexion.php"); 

 
$ID_CANDIDATO = $_POST['ID_CANDIDATO'];
$ID_EVALUACION = $_POST['ID_EVALUACION'];


$conexion->set_charset("utf8");



	if ($result = $conexion->query("SELECT * FROM medico_clinica01 C01 INNER JOIN medico_clinica02 C02 ON C01.ID_CANDIDATO = C02.ID_CANDIDATO AND C01.ID_EVALUACION = C02.ID_EVALUACION INNER JOIN medico_clinica03 C03 ON C01.ID_CANDIDATO = C03.ID_CANDIDATO AND C01.ID_EVALUACION = C03.ID_EVALUACION INNER JOIN medico_clinica04 C04 ON C01.ID_CANDIDATO = C04.ID_CANDIDATO AND C01.ID_EVALUACION = C04.ID_EVALUACION INNER JOIN medico_clinica05 C05 ON C01.ID_CANDIDATO = C05.ID_CANDIDATO AND C01.ID_EVALUACION = C05.ID_EVALUACION INNER JOIN medico_clinica06 C06 ON C01.ID_CANDIDATO = C06.ID_CANDIDATO AND C01.ID_EVALUACION = C06.ID_EVALUACION INNER JOIN medico_clinica07 C07 ON C01.ID_CANDIDATO = C07.ID_CANDIDATO AND C01.ID_EVALUACION = C07.ID_EVALUACION INNER JOIN medico_clinica08 C08 ON C01.ID_CANDIDATO = C08.ID_CANDIDATO AND C01.ID_EVALUACION = C08.ID_EVALUACION INNER JOIN medico_clinica09 C09 ON C01.ID_CANDIDATO = C09.ID_CANDIDATO AND C01.ID_EVALUACION = C09.ID_EVALUACION INNER JOIN medico_clinica10 C10 ON C01.ID_CANDIDATO = C10.ID_CANDIDATO AND C01.ID_EVALUACION = C10.ID_EVALUACION INNER JOIN medico_clinica11 C11 ON C01.ID_CANDIDATO = C11.ID_CANDIDATO AND C01.ID_EVALUACION = C11.ID_EVALUACION INNER JOIN medico_clinica12 C12 ON C01.ID_CANDIDATO = C12.ID_CANDIDATO AND C01.ID_EVALUACION = C12.ID_EVALUACION INNER JOIN medico_clinica13 C13 ON C01.ID_CANDIDATO = C13.ID_CANDIDATO AND C01.ID_EVALUACION = C13.ID_EVALUACION INNER JOIN medico_clinica14 C14 ON C01.ID_CANDIDATO = C14.ID_CANDIDATO AND C01.ID_EVALUACION = C14.ID_EVALUACION INNER JOIN medico_clinica15 C15 ON C01.ID_CANDIDATO = C15.ID_CANDIDATO AND C01.ID_EVALUACION = C15.ID_EVALUACION WHERE C01.ID_CANDIDATO = '$ID_CANDIDATO' AND C01.ID_EVALUACION = '$ID_EVALUACION'")) {

		while($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $myArray[] = $row;
    	}
    	echo json_encode($myArray,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    	$result -> close();

    }


$conexion -> close();
?>