SELECT candidatos.ID_CANDIDATO, evaluacion.ID_EVALUACION, CONCAT(PRIMER_NOMBRE, " ", SEGUNDO_NOMBRE, " ", PRIMER_APELLIDO, " ", SEGUNDO_APELLIDO) AS NOMBRE, asistencia.PRUEBA, 
IF((asistencia.ASISTENCIAS IS NULL OR asistencia.ASISTENCIAS = 0) OR asistencia.PRUEBA != "FECHA_ISE_DOCUMENTOS","No asistió", "Asistió") AS ASISTENCIAS 
FROM candidatos INNER JOIN evaluacion ON (candidatos.ID_CANDIDATO = evaluacion.ID_CANDIDATO) LEFT JOIN asistencia ON (evaluacion.ID_CANDIDATO = asistencia.ID_CANDIDATO) 
WHERE EVALUACION.FECHA_ISE_DOCUMENTOS = "2018-01-03 09:00:00"

wwewe
