<?php
header("Content-Type: text/html;charset=utf-8");
include("../../conection.php");
include("../../MySqlConnect.php");

$ID_EVALUACION = $_POST['ID_EVALUACION'];

    $sql = sprintf("SELECT *,(SELECT DATE(GREATEST (E.FECHA_EXAMEN_TOXICOLOGICO,E.FECHA_EXAMEN_PSICOLOGICO,E.FECHA_ISE_DOCUMENTOS,E.FECHA_ISE_ENTREVISTA,E.FECHA_EXAMEN_MEDICO,E.FECHA_EXAMEN_POLIGRAFICO,IF(R.FECHA_CAMBIO_RES_TOX IS NULL,'',R.FECHA_CAMBIO_RES_TOX),IF((SELECT E1.FECHA_EXAMEN_POLIGRAFICO FROM evaluacion E1 WHERE E1.EVALUACION_DERIVADA_DE =E.ID_EVALUACION) IS NULL,'',(SELECT E1.FECHA_EXAMEN_POLIGRAFICO FROM evaluacion E1 WHERE E1.EVALUACION_DERIVADA_DE =E.ID_EVALUACION) ))) AS mayor FROM evaluacion E LEFT JOIN reportes R ON E.ID_EVALUACION = R.ID_EVALUACION WHERE E.ID_EVALUACION = '%s') as mayor FROM CONCENTRADO_INFORMACION WHERE ID_EVALUACION LIKE '%s';",$ID_EVALUACION,$ID_EVALUACION);

    $conexion = new MySqlConnect($db, $user, $pswd);
    $conexion -> executeSelectQuery($sql, TRUE);
    $conexion->closeMySqlConnection();
?>